linters-settings:
  gocritic:
    disabled-checks:
      - ifElseChain

linters:
  disable:
    - funlen
    - lll
    - gochecknoglobals
    - gochecknoinits
    - goerr113
    - godox
    - gomnd
    - gosec
    - nakedret
    - wsl
  enable:
    - asciicheck
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - dupl
    - errcheck
    - exportloopref
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofmt
    - goimports
    - golint
    - gomodguard
    - goprintffuncname
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nestif
    - nolintlint
    - prealloc
    - rowserrcheck
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace

issues:
  # Excluding configuration per-path, per-linter, per-text and per-source
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - dupl
        - errcheck
        - goconst
        - gocyclo
        - gosec
        - structcheck
        - stylecheck
        - unused
